### PR TITLE
Retry usb control transfers if no data is returned

### PR DESCRIPTION
**Pull request by robho**
I have a power switch with usb id 04b4:fd13 which doesn't reliably
respond to usb control transfers. Sometimes it returns 0 bytes which
causes pysispm to give unexpected data.

I've added functionality to retry usb commands when we expect response
data, but we don't get any. A similar retry mechanism is already present
in the sispmctl tool. See here:
https://sourceforge.net/p/sispmctl/git/ci/master/tree/src/sispm_ctl.c#l53

Signed-off-by: Robert Högberg <robert.hogberg@gmail.com>

### CODE REVIEW

**Comment by xypron** [comment]
Hello Robert (@robho),

thank you for your contribution. Your patch does not consider the changes in your prior patch. Please, rebase.

Best regards

Heinrich

**Comment by xypron** [comment]
Hello Robert (@robho),

Sispmctl uses:
`src/sispm_ctl.c:50:    usleep(500*i)`
So the pause get's longer in each call. The initial duration is 500 µs.

Your code uses 50 ms in each call. Why do you wait 100 times as long as sispmctl?

Looking at https://github.com/python/cpython/blob/master/Modules/timemodule.c it seems that Python cannot sleep for less then 1000 µs. So shouldn't we start with that duration?

Best regards

Heinrich

**Comment by robho** [comment]
I haven't thought much about the delay.

I now tried setting the delay to 1 ms and ran a few tests. Most of the time one (1) retry is enough, but I've seen two retries (2 ms delay in total) needed a few times. So, 1 ms delay and 2 or 3 tries should be enough for me to get stable results.

Would you like to keep the behaviour close to that of sispmctl and let the delay depend on the loop iteration?

----

I've also seen this error, but I haven't done anything about it:
```
  File "/home/robert/.local/lib/python3.5/site-packages/sispm/__init__.py", line 164, in switchoff
    _send_ctrl_transfer(dev, 0x21, 0x09, 0x0300 + 3 * i, 0, buf, 500)
  File "/home/robert/.local/lib/python3.5/site-packages/sispm/__init__.py", line 65, in _send_ctrl_transfer
    wIndex, data_or_wLength, timeout)
  File "/home/robert/.local/lib/python3.5/site-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/home/robert/.local/lib/python3.5/site-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/home/robert/.local/lib/python3.5/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error
```
It happens more seldom than the "no data" error that the retry loop handles, but it's relatively easy to reproduce for me. I've only seen it with switchoff()/switchon(), not getstatus().

Maybe we should retry usb commands for this error also? Any thoughts?

**Comment by xypron** [comment]
Hello Robert (@robho),

I never saw these errors. But I have only used code like the one in the example directory.

Could you, please, issue

`export LIBUSB_DEBUG=4`

before calling your application. This should provide debug output from the libusb-1.0 library on the console.

I have created branch dispose_resources where usb.util.dispose_resources() is called to free resources after using USB. Does this help?

For the wait loop I would suggest to start with waiting time=0.001 and double it in each iteration. So we would first wait 1ms, then 2 ms, 4 ms, 8 ms, and finally 16 ms.

Best Regards

Heinrich

**Comment by xypron** [comment]
When the USB interface is blocked by another process, e.g. by calling claim_interface(device, interface) I get exactly the error that you have reported. dispose_resources() does not free it. But release_interface() does.
```
Traceback (most recent call last):
  File "sispmctl.py", line 149, in <module>
    main()
  File "sispmctl.py", line 102, in main
    sispm.switchon(dev, p)
  File "/home/user/.local/lib/python3.7/site-packages/sispm/__init__.py", line 155, in switchon
    buf = dev.ctrl_transfer(0x21, 0x09, 0x0300 + 3 * i, 0, buf, 500)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error
```

**Comment by robho** [comment]
I'm running this program:
```
import sispm
import time

devices = sispm.connect()
while True:
    time.sleep(0.5)
    sispm.getid(devices[0])
    sispm.getstatus(devices[0], 1)
    sispm.switchon(devices[0], 2)
```
The program can run fine for a few minutes, then the pipe error appears. That shouldn't happen, right?

If you have made changes to branch dispose_resources, you need to push them, then I'll run tests.

(I doubt disposing the resources will help though. I've been using https://github.com/jerch/python-sispm before and it disposes the resources after use, but I'm seeing problems there also.)

I'll run some more tests and provide more information.

**Comment by xypron** [comment]
Waiting 50 ms wait in your patch should not do any harm here. So I will merge your request as is. But we should still elucidate the problem with the blocked USB device.

**Comment by xypron** [comment]
Merged. We can follow up on the pipe error in issue #5

**Pull request closed without merging**
